### ISSUE TITLE
How to edit title tag "Home" on homepage?

### ISSUE THREAD

**Issue by ghost** [getgrav/grav-theme-cacti#13]
Hmmm, I was tried to search the title tag but I cannot find it.

**Comment by flaviocopes** [comment]
The title tag is defined in https://github.com/getgrav/grav-theme-cacti/blob/develop/templates/partials/base.html.twig#L11

As you can see, if the page header has a `title` property (example: https://github.com/getgrav/grav-skeleton-multilang-site/blame/develop/pages/01.blog/an-example-post/post.en.md#L2) it will be shown, in addition to the `SITE.TITLE` which is defined in the language file (https://github.com/getgrav/grav-theme-cacti/blob/develop/languages.yaml#L2-L3)
