### ISSUE TITLE
Plugin "Markdown Font Awesome" not working

### ISSUE THREAD

**Issue by hiperterminal** [getgrav/grav-theme-cacti#28]
Hi!

I am using Cacti and when I install the plugin "[Markdown Font Awesome](https://github.com/n-parsons/grav-plugin-markdown-fontawesome)" this plugin is not working in any page. I try it in another themes and works fine, but not in Cacti (my favourite).

Many thanks for your help.

**Comment by rhukster** [comment]
how about trying shortcode core? It also has fontawesome support.

**Comment by hiperterminal** [comment]
> how about trying shortcode core? It also has fontawesome support.

Thanks! It works! I disabled markdown Font Awesome plugin and works well, but was very hard to find how to use Font Awesome in Cacti for me.

Best!
