### ISSUE TITLE
After activate theme

### ISSUE THREAD

**Issue by magikcypress** [getgrav/grav-theme-cacti#5]
Hello,

After install theme and activated, Grav say : You have'nt default.html.twig for this theme.
i created templates/default.html.twig with this code.

```
{% extends 'partials/base.html.twig' %}

{% block content %}
    {{ page.content }}
{% endblock %}
```

enjoy

**Comment by rhukster** [comment]
This is not a bug, it's just a notice to say you have pages that are expecting to use a `default` template, but the Cacti theme is not providing that.  Cacti is a blogging theme that basically has these templates:

https://github.com/getgrav/grav-theme-cacti/tree/develop/templates

`page` is the one for simple content.  That is the thing about Grav, the theme tells the system what it can display, not the CMS.  This way you can easily create custom pages and have much more flexibility.

I suggest reading this blog post: http://getgrav.org/blog/traditional-cms-platforms-and-grav as it has more information on the subject.

**Comment by magikcypress** [comment]
Sorry, my bad!  ;) Interesting article, thanks!
